import type { ProviderConfig } from '../../types';

export const PROVIDER_DEFAULTS: Record<string, ProviderConfig> = {
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com/v1',
    apiKeyFormat: 'sk-...',
    keyObtainUrl: 'https://platform.deepseek.com/api_keys',
    docsUrl: 'https://api-docs.deepseek.com',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
    supportsThinking: true,
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    apiKeyFormat: 'sk-...',
    keyObtainUrl: 'https://platform.openai.com/api-keys',
    docsUrl: 'https://platform.openai.com/docs',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic',
    baseUrl: 'https://api.anthropic.com',
    apiKeyFormat: 'sk-ant-...',
    keyObtainUrl: 'https://console.anthropic.com/keys',
    docsUrl: 'https://docs.anthropic.com',
    models: [],
    chatEndpoint: '/v1/messages',
    authHeader: 'x-api-key: ${KEY}',
    apiFormat: 'anthropic',
    type: 'chat',
    supportsThinking: true,
  },
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyFormat: 'sk-or-...',
    keyObtainUrl: 'https://openrouter.ai/keys',
    docsUrl: 'https://docs.openrouter.ai',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  siliconflow: {
    id: 'siliconflow',
    name: 'SiliconFlow',
    baseUrl: 'https://api.siliconflow.cn/v1',
    apiKeyFormat: 'sk-...',
    keyObtainUrl: 'https://cloud.siliconflow.cn',
    docsUrl: 'https://docs.siliconflow.cn',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  baidu: {
    id: 'baidu',
    name: 'Baidu Qianfan',
    baseUrl: 'https://qianfan.baidubce.com/v2',
    apiKeyFormat: '...',
    keyObtainUrl: 'https://cloud.baidu.com/product/qianfan.html',
    docsUrl: 'https://cloud.baidu.com/qianfandev/',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  alibaba: {
    id: 'alibaba',
    name: 'Alibaba Bailian',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    apiKeyFormat: 'sk-...',
    keyObtainUrl: 'https://www.aliyun.com/product/bailian',
    docsUrl: 'https://help.aliyun.com/product/aliyun-multimodal-search.html',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  zhipu: {
    id: 'zhipu',
    name: 'Zhipu AI (GLM)',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    apiKeyFormat: '...',
    keyObtainUrl: 'https://open.bigmodel.cn',
    docsUrl: 'https://open.bigmodel.cn',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
    supportsThinking: true,
  },
  moonshot: {
    id: 'moonshot',
    name: 'Moonshot (Kimi)',
    baseUrl: 'https://api.moonshot.cn/v1',
    apiKeyFormat: 'sk-...',
    keyObtainUrl: 'https://platform.moonshot.cn',
    docsUrl: 'https://platform.moonshot.cn/docs',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  tencent: {
    id: 'tencent',
    name: 'Tencent Hunyuan',
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    apiKeyFormat: '...',
    keyObtainUrl: 'https://cloud.tencent.com/product/hunyuan',
    docsUrl: 'https://cloud.tencent.com/document/product/1729',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  xfyun: {
    id: 'xfyun',
    name: 'iFlytek Spark',
    baseUrl: 'https://spark-api.xf-yun.com/v3.5',
    apiKeyFormat: '...',
    keyObtainUrl: 'https://www.xfyun.cn/doc/spark/API.html',
    docsUrl: 'https://www.xfyun.cn/doc/spark/API.html',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  lingyi: {
    id: 'lingyi',
    name: 'Lingyi (Yi)',
    baseUrl: 'https://api.lingyiwanwu.com/v1',
    apiKeyFormat: '...',
    keyObtainUrl: 'https://platform.lingyiwanwu.com',
    docsUrl: 'https://platform.lingyiwanwu.com/docs',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  doubao: {
    id: 'doubao',
    name: 'Doubao (ByteDance)',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    apiKeyFormat: '...',
    keyObtainUrl: 'https://console.volcengine.com/ark/',
    docsUrl: 'https://www.volcengine.com/docs/82379',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  qiniu: {
    id: 'qiniu',
    name: 'Qiniu AI',
    baseUrl: 'https://api.qiniu.com/v1',
    apiKeyFormat: '...',
    keyObtainUrl: 'https://www.qiniu.com/ai',
    docsUrl: 'https://developer.qiniu.com/aitokenapi',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  google: {
    id: 'google',
    name: 'Google Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    apiKeyFormat: 'AIza...',
    keyObtainUrl: 'https://aistudio.google.com/apikey',
    docsUrl: 'https://ai.google.dev/gemini-api/docs',
    models: [],
    chatEndpoint: '/models',
    authHeader: 'x-goog-api-key: ${KEY}',
    apiFormat: 'custom',
    type: 'chat',
  },
  groq: {
    id: 'groq',
    name: 'Groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    apiKeyFormat: 'gsk_...',
    keyObtainUrl: 'https://console.groq.com/keys',
    docsUrl: 'https://console.groq.com/docs',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  mistral: {
    id: 'mistral',
    name: 'Mistral AI',
    baseUrl: 'https://api.mistral.ai/v1',
    apiKeyFormat: '...',
    keyObtainUrl: 'https://console.mistral.ai',
    docsUrl: 'https://docs.mistral.ai',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity',
    baseUrl: 'https://api.perplexity.ai',
    apiKeyFormat: 'pplx-...',
    keyObtainUrl: 'https://www.perplexity.ai/settings/api',
    docsUrl: 'https://docs.perplexity.ai',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  together: {
    id: 'together',
    name: 'Together AI',
    baseUrl: 'https://api.together.xyz/v1',
    apiKeyFormat: '...',
    keyObtainUrl: 'https://api.together.xyz/settings/api-keys',
    docsUrl: 'https://docs.together.ai',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
  ollama: {
    id: 'ollama',
    name: 'Ollama (Local)',
    baseUrl: 'http://localhost:11434/v1',
    apiKeyFormat: 'none',
    keyObtainUrl: '',
    docsUrl: 'https://ollama.com',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: '',
    apiFormat: 'openai',
    type: 'chat',
  },
  xiaomi_mimo: {
    id: 'xiaomi_mimo',
    name: 'Xiaomi MiMo',
    baseUrl: 'https://token-plan-cn.xiaomimimo.com/v1',
    apiKeyFormat: 'tp-...',
    keyObtainUrl: 'https://platform.xiaomimimo.com',
    docsUrl: 'https://platform.xiaomimimo.com/docs',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
    supportsThinking: true,
    multimodal: true,
  },
  bocha: {
    id: 'bocha',
    name: 'Bocha AI (Search)',
    baseUrl: 'https://api.bocha.cn',
    apiKeyFormat: 'sk-...',
    keyObtainUrl: 'https://open.bocha.cn',
    docsUrl: 'https://bocha-ai.feishu.cn/wiki/RXEOw02rFiwzGSkd9mUcqoeAnNK',
    models: [],
    chatEndpoint: '/v1/web-search',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'custom',
    type: 'search',
  },
  replicate: {
    id: 'replicate',
    name: 'Replicate',
    baseUrl: 'https://api.replicate.com/v1',
    apiKeyFormat: 'r8_...',
    keyObtainUrl: 'https://replicate.com',
    docsUrl: 'https://replicate.com/docs',
    models: [],
    chatEndpoint: '/chat/completions',
    authHeader: 'Authorization: Bearer ${KEY}',
    apiFormat: 'openai',
    type: 'chat',
  },
};

export function getProviderDefaults(id: string): ProviderConfig | undefined {
  return PROVIDER_DEFAULTS[id];
}

export function getAllProviderDefaults(): ProviderConfig[] {
  return Object.values(PROVIDER_DEFAULTS);
}
